# Generated by Django 4.1.12 on 2023-10-10 08:40

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_no', models.CharField(blank=True, max_length=128)),
                ('street_no', models.CharField(blank=True, max_length=128)),
                ('line_1', models.CharField(blank=True, max_length=128)),
                ('line_2', models.CharField(blank=True, max_length=128)),
                ('city', models.CharField(max_length=128)),
                ('region', models.CharField(max_length=128)),
                ('postal_code', models.CharField(max_length=128)),
                ('country', django_countries.fields.CountryField(max_length=2)),
            ],
        ),
    ]
