# Generated by Django 4.1.12 on 2023-10-22 06:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="address",
            unique_together=set(),
        ),
    ]
