# Generated by Django 4.1.12 on 2023-10-12 07:01

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_alter_address_options_alter_address_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='country',
            field=django_countries.fields.CountryField(blank=True, default=None, max_length=2),
        ),
    ]
