# Generated by Django 4.1.12 on 2023-10-12 07:10

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_alter_address_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='country',
            field=django_countries.fields.CountryField(default=None, max_length=2),
        ),
    ]
