# Generated by Django 4.1.12 on 2023-11-01 03:28

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "name",
                    models.CharField(
                        error_messages={"unique": "Name already exists."},
                        help_text="Required. Unique. 128 characters or fewer.",
                        max_length=128,
                        unique=True,
                        verbose_name="name",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        error_messages={"unique": "Email already exists."},
                        help_text="Required. Unique. 128 characters or fewer.",
                        max_length=254,
                        unique=True,
                        verbose_name="email address",
                    ),
                ),
                (
                    "information",
                    models.TextField(
                        default="No information available.", verbose_name="information"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "This organization is currently active."),
                            ("inactive", "This organization is currently inactive."),
                            ("disbanded", "This organization is no longer functioning"),
                            (
                                "unknown",
                                "No information about this organization's status.",
                            ),
                        ],
                        default="unknown",
                        max_length=128,
                        verbose_name="status",
                    ),
                ),
                (
                    "address",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="common.address",
                    ),
                ),
            ],
            options={
                "verbose_name": "organization",
                "verbose_name_plural": "organizations",
            },
        ),
        migrations.CreateModel(
            name="OrganizationHasUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("staff", "Is a staff."),
                            ("doctor", "Is a registered doctor."),
                            ("patient", "Is a patient."),
                            ("owner", "Is the owner."),
                        ],
                        default="other",
                        max_length=128,
                        verbose_name="user's role",
                    ),
                ),
                ("default", models.BooleanField(default=False)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organizations.organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "user role",
                "verbose_name_plural": "user roles",
                "unique_together": {("organization", "user", "default")},
            },
        ),
    ]
