# Generated by Django 4.1.12 on 2023-10-15 14:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("organizations", "0005_alter_organization_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganizationHasUserWithRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("S", "Is a staff. E.g. Wardboy, Nurse etc."),
                            ("D", "Is a registered doctor."),
                            ("P", "Is a patient."),
                            ("O", "Is a generic user."),
                        ],
                        default="O",
                        max_length=128,
                        verbose_name="user's role",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organizations.organization",
                    ),
                ),
                (
                    "user_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "organization has user with role",
                "verbose_name_plural": "organizations have users with roles",
            },
        ),
    ]
