from django.urls import path

from ..views import (
    PrescriptionChatListCreateForPatient,
    PrescriptionChatListCreateforDoctor,
    PrescriptionDetailsDeleteForPatient,
    PrescriptionDetailsDeleteForDoctor,
    PrescriptionFeedbackCreateForDoctor,
    PrescriptionFeedbackCreateForPatient,
    PrescriptionListCreate,
    PrescriptionListForPatient,
    PrescriptionMarkAsDone,
)

urlpatterns = [
    path(
        "/we/<uuid:organization_uuid>/prescriptions",
        PrescriptionListCreate.as_view(),
        name="prescription-list-create-doctor",
    ),
    path(
        "/we/<uuid:organization_uuid>/prescriptions/<uuid:prescription_uuid>",
        PrescriptionDetailsDeleteForDoctor.as_view(),
        name="prescription-details-delete-doctor",
    ),
    path(
        "/we/<uuid:organization_uuid>/prescriptions/<uuid:prescription_uuid>/mark-as-done",
        PrescriptionMarkAsDone.as_view(),
        name="prescription-mark-as-done-doctor",
    ),
    path(
        "/we/<uuid:organization_uuid>/prescriptions/<uuid:prescription_uuid>/feedbacks",
        PrescriptionFeedbackCreateForDoctor.as_view(),
        name="prescription-feedback-for-doctor",
    ),
    path(
        "/we/<uuid:organization_uuid>/prescriptions/<uuid:prescription_uuid>/chat",
        PrescriptionChatListCreateforDoctor.as_view(),
        name="prescription-chat-for-doctor",
    ),
    path(
        "/me/prescriptions",
        PrescriptionListForPatient.as_view(),
        name="prescription-list-patient",
    ),
    path(
        "/me/prescriptions/<uuid:prescription_uuid>",
        PrescriptionDetailsDeleteForPatient.as_view(),
        name="prescription-details-delete-patient",
    ),
    path(
        "/me/prescriptions/<uuid:prescription_uuid>/mark-as-done",
        PrescriptionMarkAsDone.as_view(),
        name="prescription-mark-as-done-patient",
    ),
    path(
        "/me/prescriptions/<uuid:prescription_uuid>/feedbacks",
        PrescriptionFeedbackCreateForPatient.as_view(),
        name="prescription-feedback-for-patient",
    ),
    path(
        "/me/prescriptions/<uuid:prescription_uuid>/chat",
        PrescriptionChatListCreateForPatient.as_view(),
        name="prescription-chat-for-patient",
    ),
]
