# Generated by Django 4.1.12 on 2023-10-23 03:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("organizations", "0001_initial"),
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="FeedbackForOrganization",
            new_name="FeedbackToOrganization",
        ),
        migrations.AlterField(
            model_name="messagebetweenuserorganization",
            name="from_user",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="prescription",
            name="done",
            field=models.BooleanField(default=False),
        ),
    ]
