# Generated by Django 4.1.12 on 2023-10-10 08:40

import uuid

import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import accounts.managers
import accounts.models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useraccount',
            options={'verbose_name': 'user account', 'verbose_name_plural': 'user accounts'},
        ),
        migrations.AlterModelManagers(
            name='useraccount',
            managers=[
                ('objects', accounts.managers.UserAccountManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='last_name',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='common.address'),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A+', 'A Positive'), ('A-', 'A Negative'), ('B+', 'B Positive'), ('B-', 'B Negative'), ('AB+', 'AB Positive'), ('AB-', 'AB Negative'), ('O+', 'O Positive'), ('O-', 'O Negative')], max_length=128, null=True, verbose_name='blood group'),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useraccount',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='date of birth'),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=128, null=True, verbose_name='gender'),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='height_cm',
            field=models.IntegerField(blank=True, null=True, verbose_name='height in centimetres'),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='name',
            field=models.CharField(blank=True, max_length=128, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.UserAccount._rename_photo, verbose_name='user photo'),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='weight_kg',
            field=models.IntegerField(blank=True, null=True, verbose_name='weight in kilograms'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 128 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=128, unique=True, validators=[django.contrib.auth.validators.ASCIIUsernameValidator(), django.core.validators.MinLengthValidator(8)], verbose_name='username'),
        ),
    ]
