# Generated by Django 4.1.12 on 2023-10-29 08:39

import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="blood_group",
            field=models.CharField(
                choices=[
                    ("a+", "A+"),
                    ("a-", "A-"),
                    ("b+", "B-"),
                    ("b-", "B-"),
                    ("ab+", "AB+"),
                    ("ab-", "AB-"),
                    ("o+", "O+"),
                    ("o-", "O-"),
                    ("unknown", "Unknown"),
                ],
                default="unknown",
                max_length=128,
                verbose_name="blood group",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="date_of_birth",
            field=models.DateField(
                blank=True,
                help_text="Optional. YYYY-MM-DD format.",
                null=True,
                verbose_name="date of birth",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.CharField(
                choices=[
                    ("male", "Male"),
                    ("female", "Female"),
                    ("other", "Other"),
                    ("unknown", "Unknown"),
                ],
                default="unknown",
                max_length=128,
                verbose_name="gender",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="height_cm",
            field=models.IntegerField(
                default=-1,
                validators=[django.core.validators.MinValueValidator(limit_value=1)],
                verbose_name="height in centimetres",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="Optional. 128 characters or fewer.",
                max_length=128,
                verbose_name="name",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                error_messages={"unique": "Username already exists."},
                help_text="Required. 128 characters or fewer.",
                max_length=128,
                unique=True,
                validators=[
                    django.contrib.auth.validators.ASCIIUsernameValidator(),
                    django.core.validators.MinLengthValidator(limit_value=8),
                ],
                verbose_name="username",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="weight_kg",
            field=models.IntegerField(
                default=-1,
                validators=[django.core.validators.MinValueValidator(limit_value=1)],
                verbose_name="weight in kilograms",
            ),
        ),
    ]
