# Generated by Django 4.1.12 on 2023-10-10 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_useraccount_options_alter_useraccount_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='blood_group',
            field=models.CharField(choices=[('A+', 'A Positive'), ('A-', 'A Negative'), ('B+', 'B Positive'), ('B-', 'B Negative'), ('AB+', 'AB Positive'), ('AB-', 'AB Negative'), ('O+', 'O Positive'), ('O-', 'O Negative'), ('U', 'Unknown')], default=('U', 'Unknown'), max_length=128, verbose_name='blood group'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('U', 'Unknown')], default=('U', 'Unknown'), max_length=128, verbose_name='gender'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='height_cm',
            field=models.IntegerField(default=-1, verbose_name='height in centimetres'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='weight_kg',
            field=models.IntegerField(default=-1, verbose_name='weight in kilograms'),
        ),
    ]
