# Generated by Django 4.1.12 on 2023-10-17 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("organizations", "0007_alter_organizationhasuserwithrole_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="MedicineGeneric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=128, unique=True, verbose_name="name"),
                ),
                (
                    "slug",
                    models.SlugField(
                        editable=False,
                        unique=True,
                        verbose_name="slug generated from name",
                    ),
                ),
                (
                    "pharmacology",
                    models.TextField(
                        default="Not available.",
                        verbose_name="medicine generic pharmacology",
                    ),
                ),
                (
                    "indications",
                    models.TextField(
                        default="No known indications.",
                        verbose_name="medicine generic indications",
                    ),
                ),
                (
                    "interactions",
                    models.TextField(
                        default="No known interactions.",
                        verbose_name="medicine generic interactions",
                    ),
                ),
                (
                    "side_effects",
                    models.TextField(
                        default="No known side effects.",
                        verbose_name="medicine generic side effects",
                    ),
                ),
            ],
            options={
                "verbose_name": "medicine generic",
                "verbose_name_plural": "medicine generics",
            },
        ),
        migrations.CreateModel(
            name="MedicineBrand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=128, unique=True, verbose_name="name"),
                ),
                (
                    "slug",
                    models.SlugField(
                        editable=False,
                        unique=True,
                        verbose_name="slug generated from name",
                    ),
                ),
                (
                    "medicine_generic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="medicines.medicinegeneric",
                    ),
                ),
                (
                    "owner_organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "medicine brands",
                "verbose_name_plural": "medicine brands",
            },
        ),
        migrations.CreateModel(
            name="MedicineBrandHasDosageFormWithInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dosage_form",
                    models.CharField(
                        choices=[
                            ("T", "Tablet"),
                            ("S", "Capsule"),
                            ("O", "Ointment"),
                            ("I", "Tablet"),
                        ],
                        max_length=128,
                        verbose_name="medicine brand dosage form",
                    ),
                ),
                (
                    "dosage_instructions",
                    models.TextField(
                        default="As prescribed by the doctor.",
                        verbose_name="medicine brand dosage instructions",
                    ),
                ),
                (
                    "unit_price",
                    models.IntegerField(default=-1, verbose_name="unit price in bdt"),
                ),
                (
                    "medicine_brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="medicines.medicinebrand",
                    ),
                ),
            ],
            options={
                "verbose_name": "medicine brand has dosage form with info",
                "verbose_name_plural": "medicine brands have dosage forms with info",
                "unique_together": {("medicine_brand", "dosage_form")},
            },
        ),
    ]
