# Generated by Django 4.1.12 on 2023-10-22 08:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("medicines", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="medicinebrand",
            options={
                "verbose_name": "medicine brand",
                "verbose_name_plural": "medicine brands",
            },
        ),
    ]
