# Generated by Django 4.1.12 on 2023-10-29 08:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medicines", "0002_alter_medicinebrand_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medicinebrandhasdosageformwithinfo",
            name="dosage_form",
            field=models.CharField(
                choices=[
                    ("tablet", "Tablet."),
                    ("capsule", "Capsule."),
                    ("ointment", "Ointment."),
                    ("injection", "Injection."),
                ],
                max_length=128,
                verbose_name="dosage form",
            ),
        ),
    ]
